### ISSUE TITLE
ArrayIndexOutOfBoundsException Error

### ISSUE THREAD

**Issue by kaljade** [stefanvictora/hue-scheduler#17]
Firstly I'd like to thank you for all the hard work you've put into this project, this is exactly the solution I've been looking for!

I've done a few projects on the RPi in the past, but I've never used Docker before, so this issue is most likely user error but any assistance you could offer would be greatly appreciated.

This is the error I'm seeing in Docker logs, and I've also attached my Input.txt file, for you to examine: 

`SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
2024-12-17 04:47:03,497 [init] - Connected to 172.15.15.99.
Failed to parse configuration line 'g81	civil_dusk		bri:75%		ct:3400		tr-before:1h':
ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1`

[Input.txt](https://github.com/user-attachments/files/18154889/Input.txt)

Let me know if you need any additional information to troubleshoot?

Kind regards,

Kal

**Comment by kaljade** [comment]
I tried replacing the group with the individual lights in the group in case the smart plug was throwing the error, but still no joy:
`SLF4J(I): Connected with provider of type [ch.qos.logback.classic.spi.LogbackServiceProvider]
2024-12-17 05:20:34,074 [init] - Connected to 172.15.15.99.
Failed to parse configuration line '6, 8, 9, 10	civil_dusk		bri:75%ct:3400		tr-before:1h':
ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1`

**Comment by kaljade** [comment]
Looks like it was a formatting issue with my Input.txt file, I've added both a space and a tab between each value and now it's working!

You can close this issue

**Comment by kaljade** [comment]
Looks like it was a formatting issue with my Input.txt file, I've added both a space and a tab between each value and now it's working!

Closing this issue

**Comment by stefanvictora** [comment]
Hi Kal, thank you for the kind words and opening the issue! Glad to hear that you could resolve it -- looking at the rather unhelpful ArrayIndexOutOfBoundsException that is thrown, I think I can definitely improve the user feedback in such cases.

Feel free to open another issue for any additional question or feature requests!

**Comment by stefanvictora** [comment]
I had a look at the affected code and noticed it failed to handle properties separated by multiple tabs. I fixed the issue with **0.12.2** and improved the error message if the given property is incorrectly formatted otherwise.

Thanks for bringing this up!

**Comment by kaljade** [comment]
Thank you for the update!

I'm definitely guilty of using multiple tabs, my OCD likes my input file columns to be aligned, haha.

I'm absolutely loving Hue Scheduler, I'll download the new version when I get home (do I just stop the container, update the docker-compose file and restart, or do I need to remove the container and recompose?).

Sorry for the noob question, but docker is  definitely outside my wheelhouse.

Cheers,

Kal

**Comment by stefanvictora** [comment]
Yeah, same, it definitely looks a lot nicer to have them aligned, especially for bigger configurations.

And glad to hear! To update your docker container via docker-compose you can run the following two commands in order: `docker compose pull` (load any new version of the image) and `docker compose up -d` (recreate the container if needed).

Personally, I'm using a tool called [watchtower](https://github.com/containrrr/watchtower) to automate this process for all my containers.

Hope this helps!
